version: '3.8'

services:

  main:
    image: ${LOCAL_DOCKER_IMAGE}

    environment:
        - PROJECT_NAME=${PROJECT_NAME}

    volumes:
    - type: bind
      source: ./
      target: /home/docky/hidman

    devices:
      - "/dev/input/event18:/dev/input/hidman0"

    command: terminator
