version: '3.7'

services:

  hidman-server:
    image: iitschri/hidman:${RELEASE_TAG}
    command: python3 /usr/local/src/hidman/apps/python-examples/server.py
    devices:
      - ${HIDMAN_DEVICE}:/dev/input/hidman0

  hidman-client:
    image: iitschri/hidman:${RELEASE_TAG}
    command: python3 /usr/local/src/hidman/apps/python-examples/client_timeout.py
    depends_on:
      - hidman-server
