version: '3.7'

services:

  hidman-server:
    image: iitschri/hidman:${RELEASE_TAG}
    command: python3 hidserver.py -d ${HID_DEVICE}

  hidman-client:
    image: iitschri/hidman:${RELEASE_TAG}
    command: python3 hidclient.py -s localhost
    depends_on:
      - hidman-server
