version: '3.7'

services:

  evdev-inputs:
    image: iitschri/hidman:latest

    command: python3 /usr/local/src/hidman/apps/python-examples/loop.py

    devices:
      - ${HIDMAN_DEVICE}:/dev/input/hidman0

    privileged: true
    stdin_open: true
    tty: true

    volumes:
      - type: bind
        source: ../
        target: /usr/local/src/hidman
